name: Build and Release ZIP (Split 5GB)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.0.0*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo kamu
        uses: actions/checkout@v4

      - name: Clone Xiaomi Kernel Source
        run: |
          git clone -b ruby-s-oss https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel-source

      - name: Install zip (jika belum ada)
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Compress dan Split ZIP (5GB per part)
        run: |
          zip -s 5g kernel_ruby-s-oss.zip -r kernel-source

      - name: List hasil split
        run: ls -lh

      - name: Upload semua part ke Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kernel_ruby-s-oss.zip
            kernel_ruby-s-oss.z*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
