name: Build and Release TGZ

on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.0.0*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo kamu
        uses: actions/checkout@v4

      - name: Clone Xiaomi Kernel Source
        run: |
          git clone -b ruby-s-oss https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel-source

      - name: Compress ke TGZ
        run: |
          tar -czvf xiaomi_kernel_ruby-s-oss.tgz kernel-source

      - name: Upload ke Release
        uses: softprops/action-gh-release@v2
        with:
          files: xiaomi_kernel_ruby-s-oss.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
